package solvers;
//PROBLEM 2
//Each new term in the Fibonacci sequence is generated by adding the previous two terms.
//By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//By considering the terms in the Fibonacci sequence whose values do not exceed four million,
//find the sum of the even-valued terms.
public class EvenFibonacci extends EulerSolver
{

  @Override
  public void main()
  {
    printExample(evenFibonacci(100));
    printSolution(evenFibonacci(4_000_000));
  }

  public int evenFibonacci(int limit)
  {
    int acc = 0;
    int num1 = 1;
    int num2 = 1;
    while(num2<limit) {
      acc += num2%2==0 ? num2 : 0;
      int temp = num2;
      num2 += num1;
      num1 = temp;
    }
    return acc;
  }
}
